#Alberto Rapisarda
#Back Rooms game


#import sys module, time module and choice from random module
import sys
import time
from random import choice
#lines delay
a = 1.2
#dialogues delay
b = 0.2

def intro():
    path = input('You are in a mysterious room, in front of you there are three paths\nwhich you decide? [right/left/center] ')
    path.lower()
    if path == 'right':
        face()
    elif path == 'left':
        skin()
    elif path == 'center':
        hound()
    else:
        print('Wrong input..')
        time.sleep(a)
        intro()

def skin():
    print()
    print()
    print('Left corridor, darkness, no rumors')
    time.sleep(a)
    print('you encounter your first entity')
    time.sleep(a)
    print('Seems quiet, pale and 7 feets tall') 
    time.sleep(a)
    print('sometimes he just moans softly like in pain') 
    time.sleep(a)
    print('and every breath you take he has chills.')
    time.sleep(a)
    pathS = input('He’s looking at you! But he seems docile and not dangerous, what will you do? [Run/Talk/Touch]')
    pathS.lower()
    if pathS == 'run':
        traveler()
    elif pathS == 'talk':
        Dullers()
    elif pathS == 'touch':
        firstDeath()
    else:
        print('Wrong input')
        time.sleep(a)
        skin()

def hound():
    print()
    print()
    print('You follow the central corridor')
    time.sleep(a)
    print('all the walls seem the same')
    time.sleep(a)
    print('and all the other rooms have the same disgusting smell like an abandoned house.')
    time.sleep(a)
    print('You see from distance a strange shadow')
    time.sleep(a) 
    print('a mix between a dog and a woman with the long hairs')
    time.sleep(a)
    pathH = input('You are scared and you don’t know what to do [Follow/Ignore/Call]')
    pathH.lower()
    if pathH == 'follow':
        clumps()
    elif pathH == 'ignore':
        lost()
    elif pathH == 'call':
        moths()
    else:
        print('Wrong input')
        time.sleep(a)
        hound()

def face():
    print()
    print()
    print('Still scared you try to understand where you are')
    time.sleep(a)
    print('your instinct suggests to move fast and try to look for an exit.')
    time.sleep(a)
    print('In the darkness of the corridor you see a small child playing all alone with a sort of ball,')
    time.sleep(a)
    print('but when you focus your view on him you see that he is faceless.')
    time.sleep(a)
    pathF = input('What are you going to do now? [Follow/Attack/Run]')
    pathF.lower()
    if pathF == 'follow':
        candle()
    elif pathF == 'attack':
        disease()
    elif pathF == 'run':
        flRoom()
    else:
        print('wrong input')
        time.sleep(a)
        face()

def traveler():
    print()
    print()
    print('You ignore the strange figure and you keep walking in the corridor.')
    time.sleep(a)
    print('Suddenly someone touches your shoulder,')
    time.sleep(a)
    print('Seems like another human being.')
    time.sleep(a)
    print('His name is Josh and is trapped with you in here.')
    time.sleep(a)
    josh = '"Good lord I’m save now, I’ve been trapped here since..since..I don’t know anymore please come with me, I think I find the exit"'
    #for loop to display characters one by one
    for character in josh:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    pathT = input('\nDo you trust him? [Ignore/Follow/Attack]')
    pathT.lower()
    if pathT == 'ignore':
        inf()
    elif pathT == 'follow':
        game()
    elif pathT == 'attack':
        who()
    else:
        print('Wrong input')
        time.sleep(a)
        traveler()

def Dullers():
    print()
    print()
    print('Slowly you try to speak with the creature but she seems to say only small confused words')
    time.sleep(a)
    print()
    print()
    skin = '"Keep going...second door...Dullers..Dullers"'

    for character in skin:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nA sort of irresistible driving force lets you trust this strange entity and you follow his indications.')
    time.sleep(a)
    print('After a couple of meters you arrive in this big room populated by a sort of humanoid')
    time.sleep(a)
    print('black figures that build a sort of settlement in there')
    time.sleep(a)
    pathD = input('They seems peaceful but only god knows what they really are [Ignore/Talk/Attack]')
    pathD.lower()
    if pathD == 'ignore':
        game()
    elif pathD == 'talk':
        inf()
    elif pathD == 'attack':
        wrong()
    else:
        print('Wrong input')
        Dullers()

def who():
    print()
    print()
    print('Josh keeps talking, he sounds mad and confused')
    time.sleep(a)
    print('You don’t trust this guy')
    time.sleep(a)
    print('if is a real human being or less')
    time.sleep(a)
    print('So you pretend to listen to him')
    time.sleep(a)
    print('and right when he turns you take one of shoe lace and you suffocate him')
    time.sleep(a)
    print('Slowly Josh falls down')
    time.sleep(a)
    print('pale and motionless')
    time.sleep(a)
    print('You start to feel a strange sensation')
    time.sleep(a)
    print('you feel a sort of power growing inside of you')
    time.sleep(a)
    print('and an urgent need to laugh')
    time.sleep(a)
    print('you cannot stop')
    time.sleep(a)
    print('You need to kill more and more')
    time.sleep(a)
    print('it is your destiny now')
    time.sleep(a)
    print('Your skin is pale...')
    time.sleep(a)
    print('you lost your face...')
    time.sleep(a)
    print('and you are hungry more than you ever have been in your life')
    time.sleep(a)
    print('Who are you now...?')
    time.sleep(a)
    print('GAME OVER')
    time.sleep(a)
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')    
        time.sleep(a)

def firstDeath():
    print()
    print()
    print('The creature is still looking at you, it’s actually studying you')
    time.sleep(a)
    print('Slowly you try to touch his transparent skin to understand if it is all just a dream or a nightmare')
    time.sleep(a)
    print('The creature screams so loud that you cannot even understand what is going on')
    time.sleep(a)
    print('and while you try to regain consciousness')
    time.sleep(a)
    print('is too late')
    time.sleep(a)
    print('Half of your skin is already gone in his body')
    time.sleep(a)
    print('he doesn’t stop until you are dead')
    time.sleep(a)
    print('GAME OVER')
    time.sleep(a)
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')    

def clumps():
    print()
    print()
    print('Despite the speed of the Hound')
    time.sleep(a)
    print('you are able to follow him for all the corridors')
    time.sleep(a)
    print('at the end he seems to disappear somewhere inside a wall')
    time.sleep(a)
    print('also the environment is different')
    time.sleep(a)
    print('the walls are more consumed by the mould')
    time.sleep(a)
    print('and the neons are more noisy and less bright')
    time.sleep(a)
    print()
    print()
    you = '"Maybe I\'m on another level?"'
    for character in you:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nWhile you ask yourself that')
    time.sleep(a)
    print('you see something moving on the roof')
    time.sleep(a)
    print('something like a bush of lianas in moving')
    time.sleep(a)
    print('but those are not lianas...those are human arms hanging and moving slowly')
    time.sleep(a)
    pathC = input('This place is getting worse, what will you do now? [ignore/touch/run]')
    pathC.lower()
    if pathC == 'ignore':
        inf()
    elif pathC == 'touch':
        eat()
    elif pathC == 'run':
        game()
    else:
        print('Wrong input')
        time.sleep(a)
        clumps()

def lost():
    print()
    print()
    print('The shadow of the Hound runs faster in the opposite direction')
    time.sleep(a)
    print()
    print()
    you = '"What the hell was that? I should probably go somewhere else and run away form this this place"'
    for character in you:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nYou took another corridor...and another one')
    time.sleep(a)
    print('and another one too')
    time.sleep(a)
    print('they all seem the same')
    time.sleep(a)
    print('How much time is passed now?')
    time.sleep(a)
    print('An hour?')
    time.sleep(a)
    print('A month?')
    time.sleep(a)
    print('A year?')
    time.sleep(a)
    print('You don’t know anymore')
    time.sleep(a)
    print('but something inside you is starting to born')
    time.sleep(a)
    print('MADNESS')
    time.sleep(a)
    print('is over for you')
    time.sleep(a)
    print('you are one of them now')
    time.sleep(a)
    print('one of these entities that live in this forsaken place')
    time.sleep(a)
    print('is over..')
    time.sleep(a)
    print('GAME OVER')
    time.sleep(a)
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')    

def moths():
    print()
    print()
    you = '"Hey, come here again! Who are you? What is this place? Come back here!"'
    for character in you:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nShouting this was worthless')
    time.sleep(a)
    print('the mysterious shadow ran away')
    time.sleep(a)
    print('still confused')
    time.sleep(a)
    print('you try to explore the nearby rooms')
    time.sleep(a)
    print('all similar')
    time.sleep(a)
    print('all without an exit or just a living being')
    time.sleep(a)
    print('suddenly something leans on your shoulder')
    time.sleep(a)
    print('is a moth')
    time.sleep(a)
    print('a big moth')
    time.sleep(a)
    print('seems calm and peaceful and')
    time.sleep(a)
    print('while you are looking at it')
    time.sleep(a)
    print('more moths are coming near you')
    time.sleep(a)
    pathM = input('If something can live here It means that maybe there is an exit somewhere![run/touch/follow]')
    pathM.lower()
    if pathM == 'run':
        inf()
    elif pathM == 'touch':
        small()
    elif pathM == 'follow':
        hive()
    else:
        print('Wrong input')
        moths()

def candle():
    print()
    print()
    print('The small child seems a peaceful creature')
    time.sleep(a)
    print('and in this place of pure madness you need an ally')
    time.sleep(a)
    print('he seems to go somewhere in the darkness')
    time.sleep(a)
    print('so you decide to follow him')
    time.sleep(a)
    print('despite your insecurities and the fear of the dark')
    time.sleep(a)
    print('you keep walking for an indefinite amount of time')
    time.sleep(a)
    print('the more you walk')
    time.sleep(a)
    print('the more the ambient becomes darker and scarier')
    time.sleep(a)
    print('maybe that wasn\'t a good idea')
    time.sleep(a)
    print('a small light appears at the end of the end of the corridor')
    time.sleep(a)
    print('so you try to ask for help')
    time.sleep(a)
    print('but nobody answers you')
    time.sleep(a)
    print('instead')
    time.sleep(a)
    print('the small light moves faster to your direction')
    time.sleep(a)
    print('a woman')
    time.sleep(a)
    print('seven feets tall')
    time.sleep(a)
    print('without face')
    time.sleep(a)
    print('appeared with a small candle on her side and she was floating too')
    time.sleep(a)
    print('the exact moment that you realize what is going on')
    time.sleep(a)
    print('she strikes you with the candle that paralyzes you totally')
    time.sleep(a)
    print('you can’t scream or move but you are still conscious of what is happening')
    time.sleep(a)
    print('he opens her gigantic mouth')
    time.sleep(a)
    print('hides under a layer of skin')
    time.sleep(a)
    print('and she starts to eat you')
    time.sleep(a)
    print('piece by piece')
    time.sleep(a)
    print('Is over now')
    time.sleep(a)
    print('is over')
    time.sleep(a)
    print('GAME OVER')
    time.sleep(a)
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')    

def disease():
    print()
    print()
    print('Since you came down to this place')
    time.sleep(a)
    print('you don’t trust anything or anyone')
    time.sleep(a)
    print('this child all alone in the darkness?')
    time.sleep(a)
    print('faceless too?')
    time.sleep(a)
    print('no!')
    time.sleep(a)
    print('While he was turned back')
    time.sleep(a)
    print('you took a small iron bar and you hit harder in the head one')
    time.sleep(a)
    print('..two..')
    time.sleep(a)
    print('three times')
    time.sleep(a)
    print('but every time you hit he spread a sort of blue gas from his wounds')
    time.sleep(a)
    print('but nothing can stop you')
    time.sleep(a)
    print('It’s dead now')
    time.sleep(a)
    print('and you keep walking in the opposite direction')
    time.sleep(a)
    print('trying to come back where you start')
    time.sleep(a)
    print('Suddenly you feel tired')
    time.sleep(a)
    print('your stomach hurts like never in your life')
    time.sleep(a)
    print('you start coughing harder and you see small drops of blood in your hands')
    time.sleep(a)
    print('scared you try to run but you are so tired')
    time.sleep(a)
    print('something is happening')
    time.sleep(a)
    print('you lie on the floor')
    time.sleep(a)
    print('you are dying and you don’t even know what you get..')
    time.sleep(a)
    print('you throw up blood and fever is stronger..')
    time.sleep(a)
    print('maybe some rest will be fine..')
    time.sleep(a)
    print('but while you close your eyes you already know that will be the last time for you..')
    time.sleep(a)
    print('It’s over now..')
    time.sleep(a)
    print('GAME OVER')
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')    

def flRoom():
    print()
    print()
    print('Since you came down to this place')
    time.sleep(a)
    print('you don’t trust anything or anyone')
    time.sleep(a)
    print('This child all alone in the darkness?')
    time.sleep(a)
    print('Faceless too?')
    time.sleep(a)
    print('No!')
    time.sleep(a)
    print('You run away from him')
    time.sleep(a)
    print('faster than you can!')
    time.sleep(a)
    print('After a couple of ')
    time.sleep(a)
    print('..maybe..')
    time.sleep(a)
    print('hours you decide to rest in one of the corridors near you')
    time.sleep(a)
    print('there you see a small white door')
    time.sleep(a)
    print('Soft when you touch it')
    time.sleep(a)
    print('you come inside the dark room behind this strange door')
    time.sleep(a)
    print('Right after you close the door this disappears and the lights go on')
    time.sleep(a)
    print('showing up the room')
    time.sleep(a)
    print('The room was like the inside body of some kind of animal or human being')
    time.sleep(a)
    print('the walls were covered with flesh and parts of the human body like eyes')
    time.sleep(a)
    print('mouths or noses')
    time.sleep(a)
    print('and was in constant motion')
    time.sleep(a)
    print('All the eyes are staring at you and some of the mouths are speaking strange languages')
    time.sleep(a)
    print('most of them unknown')
    time.sleep(a)
    print('but one of them says:')
    time.sleep(a)
    print()
    print()
    room = '"Who are you?"'
    for character in room:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    path = input('\nWhat do you do now? [stay/touch/run]')
    path.lower()
    if path == 'stay':
        talk()
    elif path == 'touch':
        curiosity() 
    elif path == 'run':
        noext()
    else:
        print('Wrong input')
        flRoom()

def wrong():
    print()
    print()
    print('Right before arriving at the Duller’s settlement you create a small spear with an old root')
    time.sleep(a)
    print('Right before one of them tries to approach you')
    time.sleep(a)
    print('you stab it as stronger than you can')
    time.sleep(a)
    print('The body of the Duller seems evanescent')
    time.sleep(a)
    print('that wasn\'t a good choice')
    time.sleep(a)
    print('The last thing you remember is you')
    time.sleep(a)
    print('surrounded by them and their long gray arms')
    time.sleep(a)
    print('..nothing else..')
    time.sleep(a)
    print('GAME OVER')
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')   

def eat():
    print()
    print()
    you = '"Hey there is anyone up there?"'
    for character in you:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nShouting is worthless')
    time.sleep(a)
    print('but maybe there are some real humans up there')
    time.sleep(a)
    print('So you try to grab one of those arms and pull it down')
    time.sleep(a)
    print('The arms suddenly stop waving')
    time.sleep(a)
    print('and start to block your arms and your legs')
    time.sleep(a)
    print('then another pair of them try to choke your throat')
    time.sleep(a)
    print('Nothing seems possible anymore')
    time.sleep(a)
    print('slowly the arms push you in a sort of beak in the middle')
    time.sleep(a)
    print('Now you get it..')
    time.sleep(a)
    print('that is a gigantic octopus!')
    time.sleep(a)
    print('those arms are not human..but is too late..')
    time.sleep(a)
    print('GAME OVER')
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')   

def small():
    print()
    print()
    print('Such beautiful creatures')
    time.sleep(a)
    print('so fragile')
    time.sleep(a)
    print('you finally saw something alive in this place that really don’t want to hurt you')
    time.sleep(a)
    print('You touch that little creature')
    time.sleep(a)
    print('and immediately two of them land on your other shoulder')
    time.sleep(a)
    print('and other three on your leg')
    time.sleep(a)
    print('You are a little concerned about what is going on')
    time.sleep(a)
    print('but as far they are just sixt is just fine..')
    time.sleep(a)
    print('so you try to continue your journey')
    time.sleep(a)
    print('Every move you take many and many stick to you')
    time.sleep(a)
    print('they start like pinching')
    time.sleep(a)
    print('and you feel tired')
    time.sleep(a)
    print('You are covered now..')
    time.sleep(a)
    print('they are spitting a sort of intestinal fluid..')
    time.sleep(a)
    print('that’s explain the pinching..')
    time.sleep(a)
    print('maybe it\'s time to lay down a little bit..')
    time.sleep(a)
    print('just to rest..')
    time.sleep(a)
    print('close your eyes traveler..')
    time.sleep(a)
    print('is over now..')
    time.sleep(a)
    print('GAME OVER')
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')   
        
def hive():
    print()
    print()
    you = '"If something can live here it means that there is an exit somewhere!"'
    for character in you:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nAll the moths come from a door')
    time.sleep(a)
    print('so you decide to follow the swarm')
    time.sleep(a)
    print('the environment changed')
    time.sleep(a)
    print('the walls are sticky and covered with something like a gray honey that tastes bad')
    time.sleep(a)
    print('The moths are bigger now')
    time.sleep(a)
    print('and more aggressive..')
    time.sleep(a)
    print('this place is somehow a big hive')
    time.sleep(a)
    print('There it is..')
    time.sleep(a)
    print('a small window..')
    time.sleep(a)
    print('it’s all black outside but I can feel the wind again!')
    time.sleep(a)
    print('Walking in that honey is not easy..')
    time.sleep(a)
    print('but you need to do this!')
    time.sleep(a)
    print('One enormous shadow appears right in front of you')
    time.sleep(a)
    print('you turn slowly just to see what was going on')
    time.sleep(a)
    print('The Queen..')
    time.sleep(a)
    print('for sure..')
    time.sleep(a)
    print('is looking at you')
    time.sleep(a)
    print('..shaking her wings nervously and emitting a strange green liquid from the mouth')
    time.sleep(a)
    print('You couldn’t even breathe that she sprayed that liquid on you..')
    time.sleep(a)
    print('intestinal liquids..')
    time.sleep(a)
    print('and now she’s calling the rest of the hive.')
    time.sleep(a)
    print('Larves everywhere..')
    time.sleep(a)
    print('big larves of course')
    time.sleep(a)
    print('..big larves of course, are surrounding you and eating your melted flesh greedily')
    time.sleep(a)
    print('..you were so close..')
    time.sleep(a)
    print('so close..')
    time.sleep(a)
    print('GAME OVER')    
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')   

def talk():
    print()
    print()
    r1 = '"Who are you?"'
    for character in r1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nRepeats insistently the room')
    time.sleep(a)
    print()
    print()
    y1 = 'I just lost myself in here..can you help me?\n'
    for character in y1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    r2 = 'Exit from here is not easy..but not impossible..you have to go on the 389 level and meet the Game Master\n'
    for character in r2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    y2 = 'The Game Master?\n'
    for character in y2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    r3 = 'Yes, he will lead you to the right path..but this will not be so easy..\n'
    for character in r3:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    y3 = 'Why?\n'
    for character in y3:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    r4 = 'I said too much now. Get out of me now and keep following the corridors'
    for character in r4:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nThe room starts to be nervous and angry so you follow its instructions.')
    time.sleep(a)
    print('The travel was incredibly long but luckily safe')
    time.sleep(a)
    print('The new level is a boiler room')
    time.sleep(a)
    print('full of corridors made by steamy pipes illuminated by just a red light..')
    time.sleep(a)
    print()
    print()
    gm = 'Let\'s play a game..'
    for character in gm:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nA voice echoes in the room..this thing seems near you...but you keep walking')
    time.sleep(a)
    print()
    print()
    gm2 = 'I need to play now..'
    for character in gm2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nThis time the sound comes from a small puppet on the floor, looks like a clown and it’s standing up all by itself')
    time.sleep(a)
    print()
    print()
    gm3 = 'Welcome..let\'s play a game'
    for character in gm3:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    path = input('\nWhat you will do? [play/run]')
    path.lower()
    if path == 'play':
        riddle()
    elif path == 'run':
        nope()
    else:
        print('wrong input')
        talk()

def curiosity():
    print()
    print()
    room = '"Who are you?"'
    for character in room:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nThe room shouts')
    time.sleep(a)
    print('but you ignore that..')
    time.sleep(a)
    print('you never see something in your life')
    time.sleep(a)
    print('The whole room was a real living being')
    time.sleep(a)
    print('incredible!')
    time.sleep(a)
    print('All of this surely is one of those lucid dreams..')
    time.sleep(a)
    print('and there is only one way to get it..')
    time.sleep(a)
    print('You start to touch one of those body parts..')
    time.sleep(a)
    print('they seem really alive..')
    time.sleep(a)
    print()
    print()
    room2 = '“So you decide to ignore me”'
    for character in room2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nThe floor below you starts moving')
    time.sleep(a)
    print('that’s for sure is not a dream..')
    time.sleep(a)
    print('this is a nightmare')
    time.sleep(a)
    print('The room decided to eat you and the “floor” was')
    time.sleep(a)
    print('for the whole time')
    time.sleep(a)
    print('his mouth opened wide and you fell down in the darkness of his body..')
    time.sleep(a)
    print('guess is over now..')
    time.sleep(a)
    print('at least now you know that was not a dream..')
    time.sleep(a)
    print('GAME OVER')
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')   

def noext():
    print()
    print()
    room = '"Who are you?"'
    for character in room:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nThe room shouts to you')
    time.sleep(a)
    print('This is not possible..')
    time.sleep(a)
    print('a living room!')
    time.sleep(a)
    print('You need to go out immediately no matter what!')
    time.sleep(a)
    print('You try to run in every direction possible')
    time.sleep(a)
    print('corridors or other small rooms but nothing..')
    time.sleep(a)    
    print()
    print()
    laugh = '"AHAHAAHAHAHAHAHA"'
    for character in laugh:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nThe room starts to laugh incessantly while you keep running hopeless in this madness of faces')
    time.sleep(a)
    print('body parts and flesh')
    time.sleep(a)
    print('Suddenly the floor became sticky')
    time.sleep(a)
    print()
    print()
    room2 = '"Thanks, that was fun.."'
    for character in room2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('\nThe room now starts to emit some kind of digestive liquids from the walls')
    time.sleep(a)
    print('Running is not always  a good idea')
    time.sleep(a)
    print('but now is over..')
    time.sleep(a)
    print('surrender to your destiny and become part of the room..')
    time.sleep(a)
    print('for ever..')
    time.sleep(a)
    print('GAME OVER')
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')   

def game():
    print()
    print()
    print('All your choices led you to the sight of the Game master')
    time.sleep(a)
    print('You are in the 389 level')
    time.sleep(a)
    print('entirely built in an enormous boiler room')
    time.sleep(a)
    print('filled with steamy pipelines and illuminated by a scary red light')
    time.sleep(a)
    print('Here lives one of the scariest creatures')
    time.sleep(a)
    print('segregated forever')
    time.sleep(a)
    print('with the appearance of a puppet')
    time.sleep(a)
    print('in the last level of this madness:')
    time.sleep(a)
    print('THE GAME MASTER')
    time.sleep(a)
    print()
    print()
    gm = '"Play with me please..."'
    for character in gm:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    path = input('What you do now? [play/run]')
    path.lower()
    if path == 'play':
        riddle()
    elif path == 'run':
        nope()
    else:
        print('wrong input')
        game()

def nope():
    print()
    print()
    print('There is no exit')
    time.sleep(a)
    print('you cannot run')
    time.sleep(a)
    print('there is no other choice unless dying')
    time.sleep(a)
    print('Somethimes stepping up and jumping is the only hope')
    time.sleep(a)
    print('your hope')
    time.sleep(a)
    print('Guess it\'s too late now..')
    time.sleep(a)
    print('GAME OVER')
    time.sleep(a)
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')   

def riddle():
    print()
    print()
    gm = '“Finally..a player….finally”'
    for character in gm:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('There is no chance, you have to guess the Game Master riddle.')
    time.sleep(a)
    rid = input('"If it falls from a skyscraper it does not break, but if it falls into the water it breaks..what is it?"')
    rid.lower()
    
    #loop for the right answer
    wrong = 4
    while rid != 'paper':
        wrong -= 1
        rid = input('Wrong, you got {0} tentatives, try again: '.format(wrong))
        if wrong == 0:
            loseG()
    
    winG()

def loseG():
    print()
    print()
    print('The Game Master stays silent for a couple of minutes..')
    time.sleep(a)
    print('the pressure was sky high..')
    time.sleep(a)
    laugh = '"AHAHAHAHAHAHAAHAH"'
    for character in laugh:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('Everything stops..')
    time.sleep(a)
    print('the Game Master laughs..')
    time.sleep(a)
    print('the environment changes..')
    time.sleep(a)
    print('where you are now? ')
    time.sleep(a)
    print('Where?')
    time.sleep(a)
    #function to choose a random function in a list
    randomChapter = [skin, hound, face]
    choice(randomChapter)()

def winG():
    print()
    print()
    print('The Game Master stays silent for a couple of minutes..')
    time.sleep(a)
    print('the pressure was sky high..')
    time.sleep(a)
    print('then like out of nowhere everything stops.')
    time.sleep(a)
    print('You don’t remember anything')
    time.sleep(a)
    print('what happened?')
    time.sleep(a)
    print('What is this strange sensation?')
    time.sleep(a)
    print('The only thing you know is that you can finally feel the wind on your skin..')
    time.sleep(a)
    print('but the street in the night is still strange')
    time.sleep(a)
    print('all that silence')
    time.sleep(a)
    print('so much desolation')
    time.sleep(a)
    print('is this reality again?')
    time.sleep(a)
    print('Who cares you are tired now')
    time.sleep(a)
    print('is time to come back home')
    time.sleep(a)
    print('YOU WIN')
    time.sleep(a)
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')   

def inf():
    print()
    print()
    print('All your choices led you to the sight of the Infinity beast.')
    time.sleep(a)
    print('You are in the 188 level')
    time.sleep(a)
    print('the environment changes again..')
    time.sleep(a)
    print('you are now in a small abandoned town similar to Chernobyl.')
    time.sleep(a)
    print('Here lives the Infinity beast')
    time.sleep(a)
    print('an entity with the appearance of a goat-headed human.')
    time.sleep(a)
    print('Is the guardian of the final level of this maze')
    time.sleep(a)
    print('and his ready to cheat you and chain you to one of his loops..')
    time.sleep(a)
    print('Take care of your choices in this level..')
    time.sleep(a)
    print('nothing is real..')
    time.sleep(a)
    print('the darkest guardian has splitted for you the exit in three rooms:')
    time.sleep(a)
    print('one takes you to the exit')
    time.sleep(a)
    print('the second one to death')
    time.sleep(a)
    print('and the third one..')
    time.sleep(a)
    print('the third one only god knows what\'s inside that door')
    time.sleep(a)
    print('The dark guardian stares at you')
    time.sleep(a)
    print('bleating nervously')
    time.sleep(a)
    print('its time')
    time.sleep(a)
    door = input('What\'s your path now? [door 1/door 2/door 3]')
    door.lower()
    if door == 'door 1':
        loseI()
    elif door == 'door 2':
        winI()
    elif door == 'door 3':
        randomI()
    else:
        print('Wrong input')
        inf()

def loseI():
    print()
    print()
    beast = '"So that\'s your decision now"'
    for character in beast:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('You come through that door')
    time.sleep(a)
    print('scared of the possibilities behind that...')
    time.sleep(a)
    print('you go anyway.')
    time.sleep(a)
    print('It’s all dark now..')
    time.sleep(a)
    print('an unnatural dark silence is surrounding you..')
    time.sleep(a)
    print('you try to scream but nothing comes out of your mouth..')
    time.sleep(a)
    print('you cannot even hear your thoughts')
    time.sleep(a)
    print('What is this?')
    time.sleep(a)
    print('Where are you?')
    time.sleep(a)
    print('It’s time to rest maybe..')
    time.sleep(a)
    print('nobody can hear you..')
    time.sleep(a)
    print('it’s over finally..')
    time.sleep(a)
    print('GAME OVER')
    time.sleep(a)
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')   

def winI():
    print()
    print()
    beast = '"So that\'s your decision now"'
    for character in beast:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('You come through that door')
    time.sleep(a)
    print('scared of the possibilities behind that...')
    time.sleep(a)
    print('you go anyway.')
    time.sleep(a)
    print('what happened?')
    time.sleep(a)
    print('What is this strange sensation?')
    time.sleep(a)
    print('The only thing you know is that you can finally feel the wind on your skin..')
    time.sleep(a)
    print('but the street in the night is still strange')
    time.sleep(a)
    print('all that silence')
    time.sleep(a)
    print('so much desolation')
    time.sleep(a)
    print('is this reality again?')
    time.sleep(a)
    print('Who cares you are tired now')
    time.sleep(a)
    print('is time to come back home')
    time.sleep(a)
    print('YOU WIN')
    time.sleep(a)
    restart = input('Do you want to play again? [Y/N]')
    restart.lower()
    if restart == 'y':
        intro()
    elif restart == 'n':
        print('Bye bye then..')   

def randomI():
    print()
    print()
    beast = '"So that\'s your decision now"'
    for character in beast:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print('You come through that door')
    time.sleep(a)
    print('scared of the possibilities behind that...')
    time.sleep(a)
    print('you go anyway.')
    time.sleep(a)

    randomPaths = [skin, hound, face, traveler, Dullers, clumps, flRoom, moths]
    choice(randomPaths)()

print("""
                                           *******************
                                           *                 *
                                           *   The Bakrooms  *
                                           *                 *
                                           *******************
""")

print('''
    "If you're not careful and you noclip out of reality in the wrong areas,
    you'll end up in the Backrooms, where it's nothing but the stink of old moist carpet,
    the madness of mono-yellow, the endless background noise of fluorescent lights at maximum hum-buzz,
    and approximately six hundred million square miles of randomly segmented empty rooms to be trapped in.
    God save you if you hear something wandering around nearby,
    because it sure as hell has heard you"
''')

you = '"Where am I..?"'
for character in you:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
start = input('\nDo you want to play? [Yes/No]')
start.lower()
if start == 'yes':
    intro()
elif start == 'no':
    print('Maybe next time..')
else:
    print('Wrong answer')